[permissions]
filesystem_paths = [".", "~/VOICE.md", "../yoker", "../c3"]
blocked_write_paths = [ "~/VOICE.md" ]

[plugins]
enabled = true
packages = ["yoker_writing_assistant"]

[agents.directories]
c3 = "../c3/agents"

[skills.directories]
c3 = "../c3/skills"
